from dataclasses import dataclass
from typing import Optional, List
from src.utils.config import Config

@dataclass
class TextbookContent:
    """
    Represents textual content extracted from a textbook page
    
    Based on the entity defined in data-model.md
    """
    id: str
    url: str
    module: str
    chapter: str
    section: str
    raw_content: str
    processed_content: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class ContentChunk:
    """
    Represents a normalized text segment of appropriate size for embedding generation
    
    Based on the entity defined in data-model.md
    """
    id: str
    content_id: str
    chunk_index: int
    text: str
    token_count: int
    overlap_text: Optional[str] = ""
    hash: Optional[str] = ""
    
    def __post_init__(self):
        """Validate that the chunk complies with constitution requirements"""
        # According to the constitution: 512 tokens with 64-token overlap
        if self.token_count > Config.CHUNK_SIZE:
            raise ValueError(f"Chunk token count ({self.token_count}) exceeds constitution limit ({Config.CHUNK_SIZE})")
        
        if len(self.overlap_text) > Config.OVERLAP_SIZE:
            raise ValueError(f"Overlap text length ({len(self.overlap_text)}) exceeds constitution limit ({Config.OVERLAP_SIZE})")

@dataclass
class EmbeddingVector:
    """
    Represents a high-dimensional vector representation of content chunk generated by Cohere models
    
    Based on the entity defined in data-model.md
    """
    id: str
    chunk_id: str
    vector: List[float]
    vector_size: int
    created_at: Optional[str] = None

@dataclass
class ProcessingJob:
    """
    Represents a processing job for tracking ingestion progress
    
    Based on the entity defined in data-model.md
    """
    id: str
    status: str  # PENDING, IN_PROGRESS, COMPLETED, FAILED
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    total_pages: int = 0
    processed_pages: int = 0
    failed_pages: int = 0
    error_log: Optional[str] = ""
    resume_point: Optional[str] = ""