"""
Data models for the agent service.

These models define the structure of data used in the agent service,
based on the data-model.md specification.
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum
import time
import uuid


class UserQuery(BaseModel):
    """
    Natural language request from user requiring information retrieval and synthesis.
    """
    id: str = Field(..., description="Unique identifier for the query request")
    text: str = Field(..., min_length=3, max_length=10000, description="The actual query text from the user")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the query was received")
    session_id: Optional[str] = Field(None, description="Identifier for conversation context")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional query context and parameters")


class RetrievedChunk(BaseModel):
    """
    Content chunk from textbook returned by the retrieval pipeline.
    """
    id: str = Field(..., description="Unique identifier for this retrieved chunk")
    content: str = Field(..., description="The actual text content of the chunk")
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Semantic similarity score between query and chunk")
    rank: int = Field(..., ge=0, description="Position in the ranked results (0-indexed)")
    metadata: Dict[str, Any] = Field(..., description="Associated metadata")


class RetrievalResult(BaseModel):
    """
    Collection of retrieved chunks and metadata returned by the retrieval pipeline.
    """
    id: str = Field(..., description="Unique identifier for this retrieval result")
    tool_call_id: str = Field(..., description="Reference to the tool call that generated this result")
    chunks: List[RetrievedChunk] = Field(..., description="RetrievedChunk objects with similarity scores")
    search_parameters: Dict[str, Any] = Field(..., description="Parameters used for the search")
    total_chunks_found: int = Field(..., description="Total number of chunks found before filtering")
    execution_time_ms: float = Field(..., description="Time taken to execute the retrieval")
    retrieval_timestamp: datetime = Field(..., description="When the retrieval was performed")


class Source(BaseModel):
    """
    Source information for citation in agent responses.
    """
    url: str = Field(..., description="Source URL of the content")
    module: str = Field(..., description="Module identifier containing the chunk")
    chapter: str = Field(..., description="Chapter identifier containing the chunk")
    section: str = Field(..., description="Section title of the content")
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Similarity score of the source")
    content_preview: str = Field(..., description="Preview of the content used")
    url_fragment: Optional[str] = Field(None, description="URL fragment/anchor for direct linking to specific content")
    page_reference: Optional[str] = Field(None, description="Specific page or section reference in the textbook")


class AgentResponse(BaseModel):
    """
    Synthesized answer generated by the agent based on retrieved content.
    """
    id: str = Field(..., description="Unique identifier for the response")
    query_id: str = Field(..., description="Reference to the original user query")
    content: str = Field(..., description="The synthesized response content")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence level in the response accuracy")
    sources: List[Source] = Field(default=[], description="Citations to source materials used in synthesis")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the response was generated")
    processing_time_ms: float = Field(..., description="Time taken to generate the response")


class QueryParameters(BaseModel):
    """
    Parameters for query processing.
    """
    top_k: int = Field(default=5, ge=1, le=50, description="Number of results to retrieve")
    threshold: float = Field(default=0.6, ge=0.0, le=1.0, description="Minimum similarity threshold")
    filters: Optional[Dict[str, str]] = Field(None, description="Filters to apply to the search")


class QueryRequest(BaseModel):
    """
    Request model for the query endpoint.
    """
    query: str = Field(..., min_length=3, max_length=10000, description="The query text")
    filters: Optional[Dict[str, str]] = Field(None, description="Filters to apply to the search")
    parameters: QueryParameters = Field(default_factory=QueryParameters, description="Query processing parameters")


class ChatRequest(BaseModel):
    """
    Request model for the chat endpoint.
    """
    query: str = Field(..., min_length=3, max_length=10000, description="The query text")
    session_id: Optional[str] = Field(None, description="Session identifier for conversation context")
    parameters: QueryParameters = Field(default_factory=QueryParameters, description="Query processing parameters")


class QueryResponse(BaseModel):
    """
    Response model for the query endpoint.
    """
    result_id: str = Field(..., description="Unique identifier for the result")
    query: str = Field(..., description="The original query text")
    results: List[RetrievedChunk] = Field(..., description="Retrieved results")
    search_parameters: Dict[str, Any] = Field(..., description="Parameters used for the search")
    execution_time_ms: float = Field(..., description="Time taken to execute the search")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the response was generated")


class ChatResponse(BaseModel):
    """
    Response model for the chat endpoint.
    """
    response_id: str = Field(..., description="Unique identifier for the response")
    query: str = Field(..., description="The original query text")
    answer: str = Field(..., description="The agent-generated answer")
    sources: List[Source] = Field(default=[], description="Sources used in generating the response")
    confidence_score: float = Field(ge=0.0, le=1.0, description="Confidence score of the response")
    processing_time_ms: float = Field(..., description="Time taken to process the query")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the response was generated")


class HealthStatus(str, Enum):
    """
    Enum for health status values.
    """
    HEALTHY = "healthy"
    UNHEALTHY = "unhealthy"
    DEGRADED = "degraded"


class HealthResponse(BaseModel):
    """
    Response model for the health endpoint.
    """
    status: HealthStatus = Field(..., description="Overall health status of the service")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the health check was performed")
    dependencies: Dict[str, str] = Field(..., description="Status of various dependencies")
    metrics: Optional[Dict[str, Any]] = Field(None, description="Optional metrics about the service")