from pydantic import BaseModel, Field
from typing import List, Dict, Optional
from datetime import datetime
from dataclasses import dataclass


class QueryText(BaseModel):
    """User-provided text query for information retrieval"""
    id: str
    text: str = Field(..., min_length=3, max_length=10000)
    timestamp: datetime = Field(default_factory=datetime.now)
    session_id: Optional[str] = None
    query_metadata: Optional[Dict] = Field(default_factory=dict)


class QueryEmbedding(BaseModel):
    """Vector representation of the user query generated by Cohere models"""
    id: str
    query_id: str
    vector: List[float]
    vector_size: int
    model_used: str
    created_at: datetime = Field(default_factory=datetime.now)

    class Config:
        arbitrary_types_allowed = True


class Metadata(BaseModel):
    """Information associated with retrieved content"""
    url: str = ""
    module: str = ""
    chapter: str = ""
    section: str = ""
    chunk_index: int = 0
    hash: Optional[str] = ""


class RetrievedChunk(BaseModel):
    """Content chunk from textbook that matches the user query"""
    id: str
    query_embedding_id: str
    content: str
    similarity_score: float = Field(ge=0.0, le=1.0)
    rank: int
    metadata: Metadata


class SearchResult(BaseModel):
    """Results of the similarity search operation"""
    id: str
    query_id: str
    query_embedding_id: str
    chunks: List[RetrievedChunk]
    search_parameters: Dict[str, str]  # Includes k, threshold, distance metric
    execution_time_ms: float
    retrieval_timestamp: datetime = Field(default_factory=datetime.now)


class ValidationResult(BaseModel):
    """Validation results for retrieval outputs"""
    id: str
    search_result_id: str
    is_valid: bool
    validation_issues: List[str] = Field(default_factory=list)
    confidence_score: float = Field(ge=0.0, le=1.0)
    validation_rules_applied: List[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.now)